# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrRyxELUiif9kpiB7eq5xxBJb9iTxqPs
"""

import matplotlib.pyplot as plt

import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

x=np.array([0,3,6, 0])
y=np.array([0,150,0, 0])
plt.plot(x,y)
plt.show()

x=np.array([0,0,6, 6, 0])
y=np.array([0,140,140, 0, 0])
plt.plot(x,y, 'o:r')
plt.show()

x = np.array([0,0,6,6,3,0])
y = np.array([0,4,4,0,6,0])

plt.plot(x, y, 'o:r')
plt.show()

x1 = [0,0,6,6,0]
y1 = [0,4,4,0,0]

x2 = [0,3,6]
y2 = [4,6,4]

x3 = [2.5,2.5,3.5,3.5,2.5]
y3 = [0,2,2,0,0]

x4 = [1,1,2,2,1]
y4 = [2,3,3,2,2]

plt.plot(x1,y1,'black')
plt.plot(x2,y2,'red')
plt.plot(x3,y3,'blue')
plt.plot(x4,y4,'green')

plt.fill(x1,y1,'lightyellow')
plt.fill(x2,y2,'brown')
plt.fill(x3,y3,'saddlebrown')
plt.fill(x4,y4,'lightblue')

plt.axis('equal')
plt.show()

fanlar = ['Matematika', 'Informatika', 'Fizika', 'Kimyo', 'Biologiya', 'Ingliz tili']
ball = [85, 95, 75, 80, 70, 90]

ranglar = ['red', 'blue', 'green', 'orange', 'purple', 'cyan']

plt.bar(fanlar, ball, color=ranglar)

plt.title("Talabalar fanlardan olgan ballari")
plt.xlabel("Fanlar")
plt.ylabel("Ball")

plt.show()

oylar = ['Yan', 'Fev', 'Mar', 'Apr', 'May', 'Iyun']
savdo = [120, 150, 170, 140, 200, 230]

plt.plot(oylar, savdo, marker='o', color='blue', linewidth=3)

plt.title("Oylik savdo diagrammasi")
plt.xlabel("Oylar")
plt.ylabel("Savdo miqdori")

plt.show()

x = []
y = []

# Chap vertikal chiziq
for i in range(0,11):
    x.append(0)
    y.append(i)

# Yuqori gorizontal chiziq
for i in range(0,6):
    x.append(i)
    y.append(10)

# O‘ng vertikal (yuqori qismi)
for i in range(6,10):
    x.append(5)
    y.append(i)

# O‘rta gorizontal
for i in range(0,6):
    x.append(i)
    y.append(5)

# Pastki qiya chiziq
for i in range(0,6):
    x.append(i)
    y.append(5-i)

plt.scatter(x, y, color='green', s=70)

plt.title("Rustamjon Ziyotaliyev")
plt.axis('equal')
plt.show()

x = []
y = []

# 1-qiya chiziq
for i in range(0,11):
    x.append(i)
    y.append(i)

# 2-qiya chiziq
for i in range(0,11):
    x.append(i)
    y.append(10-i)

plt.scatter(x, y, color='green', s=120)

plt.title("Xayotbek Xalimov")
plt.axis('equal')
plt.show()

x=[]
y=[]

# --- R harfi (1) ---
for i in range(0,11):
    x.append(0)
    y.append(i)

for i in range(0,6):
    x.append(i)
    y.append(10)

for i in range(6,10):
    x.append(5)
    y.append(i)

for i in range(0,6):
    x.append(i)
    y.append(5)

for i in range(0,6):
    x.append(i)
    y.append(5-i)


# --- + belgisi ---
for i in range(3,8):
    x.append(8)
    y.append(i)

for i in range(6,11):
    x.append(i)
    y.append(5)


# --- R harfi (2) ---
shift = 14
for i in range(0,11):
    x.append(shift)
    y.append(i)

for i in range(0,6):
    x.append(i+shift)
    y.append(10)

for i in range(6,10):
    x.append(5+shift)
    y.append(i)

for i in range(0,6):
    x.append(i+shift)
    y.append(5)

for i in range(0,6):
    x.append(i+shift)
    y.append(5-i)


# --- = belgisi ---
for i in range(20,25):
    x.append(i)
    y.append(7)

for i in range(20,25):
    x.append(i)
    y.append(4)


# --- S harfi ---
shift = 27
for i in range(0,6):
    x.append(i+shift)
    y.append(10)

for i in range(6,10):
    x.append(shift)
    y.append(i)

for i in range(0,6):
    x.append(i+shift)
    y.append(5)

for i in range(1,5):
    x.append(5+shift)
    y.append(i)

for i in range(0,6):
    x.append(i+shift)
    y.append(0)


plt.scatter(x,y,s=50,color='red')
plt.axis('equal')
plt.title("R + R = S")
plt.show()